version: "3.7"

services:

  nginx:
    build: ./nginx_web_server
    restart: always
    ports:
      # Bind container port 80 to the host port 80
      - "80:80"
    depends_on:
      - flaskapp

  flaskapp:
    build: ./flask_app
    restart: always
    expose:
      # Since we'll use Gunicorn to run the application, we need to expose its
      # default port 8000, rather than the default port 5000 of Flask
      # development server.
      - 8000
      # Note that this port is only exposed to other services in the same
      # network, but not to outside world
